version: '3.4'
services:
  app:
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - ./media:/usr/share/nginx/media
    ports:
      - "${APP_PORT}:${APP_PORT}"
    image: "tribble42/react-nes"
    pull_policy: always
